server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/cambio_service
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:54320/cambio_service
    user: root
    password: admin123
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  show-actuator: true
  swagger-ui:
    config-url: /cambio-service/v3/api-docs/swagger-config
    url: /cambio-service/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka